server {
    listen 80;
    server_name localhost; # A remplacer par votre nom de domaine en ligne

    # Redirection de tout le trafic HTTP vers HTTPS (A décommenter quand SSL configuré)
    # return 301 https://$host$request_uri;

    location / {
        proxy_pass http://127.0.0.1:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs;
        proxy_cache_bypass $http_upgrade;
        
        # Securite basique headers
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options nosniff;
    }
}

# Configuration HTTPS (A décommenter quand SSL configuré avec Certbot/Let's Encrypt par exemple)
# server {
#     listen 443 ssl;
#     server_name localhost;
#
#     ssl_certificate /etc/nginx/ssl/cert.pem;
#     ssl_certificate_key /etc/nginx/ssl/key.pem;
#
#     location / {
#         proxy_pass http://backend:4000;
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection 'upgrade';
#         proxy_set_header Host $host;
#         proxy_cache_bypass $http_upgrade;
#     }
# }
